"""empty message

Revision ID: 59689e8c95b3
Revises: 01d7d2a8f7f8
Create Date: 2020-10-26 10:44:10.640841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59689e8c95b3'
down_revision = '01d7d2a8f7f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('datetime', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('article', sa.Text(), nullable=True),
    sa.Column('motion', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article')
    # ### end Alembic commands ###
